-- MySQL Script generated by MySQL Workbench
-- Sun Mar 31 01:36:08 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Actor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Actor` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Actor` (
  `TIN` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Surname` VARCHAR(45) NOT NULL,
  `Birth_Date` DATE NOT NULL,
  `Gender` ENUM('Male', 'Female') NOT NULL,
  `Nationality` VARCHAR(45) NOT NULL,
  `Category` ENUM('Self taught', 'Has studied', 'Working-Studying') NOT NULL,
  `Manager_TIN` INT NOT NULL,
  `Actor_TIN` INT NOT NULL,
  PRIMARY KEY (`TIN`),
  UNIQUE INDEX `TIN_UNIQUE` (`TIN` ASC) VISIBLE,
  INDEX `fk_Actor_Actor1_idx` (`Actor_TIN` ASC) VISIBLE,
  CONSTRAINT `fk_Actor_Actor1`
    FOREIGN KEY (`Actor_TIN`)
    REFERENCES `mydb`.`Actor` (`TIN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Manager`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Manager` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Manager` (
  `TIN` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Surname` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`TIN`),
  UNIQUE INDEX `TIN_UNIQUE` (`TIN` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Company`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Company` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Company` (
  `Name` VARCHAR(45) NOT NULL,
  `Website` VARCHAR(45) NOT NULL,
  `Phone_number` INT NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Name`),
  UNIQUE INDEX `Name_UNIQUE` (`Name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Contract`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Contract` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Contract` (
  `Date` DATE NOT NULL,
  `Duration` VARCHAR(45) NOT NULL,
  `Actor_Payment` FLOAT NOT NULL,
  `Manager_Payment` FLOAT NOT NULL,
  `Company_Name` VARCHAR(45) NOT NULL,
  `Actor_TIN` INT NOT NULL,
  `Manager_TIN` INT NOT NULL,
  PRIMARY KEY (`Date`, `Company_Name`, `Actor_TIN`),
  UNIQUE INDEX `Date_UNIQUE` (`Date` ASC) VISIBLE,
  INDEX `fk_Contract_Company1_idx` (`Company_Name` ASC) VISIBLE,
  UNIQUE INDEX `Company_Name_UNIQUE` (`Company_Name` ASC) VISIBLE,
  INDEX `fk_Contract_Actor1_idx` (`Actor_TIN` ASC) VISIBLE,
  INDEX `fk_Contract_Manager1_idx` (`Manager_TIN` ASC) VISIBLE,
  CONSTRAINT `fk_Contract_Company1`
    FOREIGN KEY (`Company_Name`)
    REFERENCES `mydb`.`Company` (`Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Contract_Actor1`
    FOREIGN KEY (`Actor_TIN`)
    REFERENCES `mydb`.`Actor` (`TIN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Contract_Manager1`
    FOREIGN KEY (`Manager_TIN`)
    REFERENCES `mydb`.`Manager` (`TIN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
PACK_KEYS = DEFAULT
ROW_FORMAT = DEFAULT;


-- -----------------------------------------------------
-- Table `mydb`.`Director`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Director` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Director` (
  `TIN` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Surname` VARCHAR(45) NOT NULL,
  `Birth_Date` DATE NOT NULL,
  `Gender` ENUM('Male', 'Female') NOT NULL,
  `Nationality` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`TIN`),
  UNIQUE INDEX `TIN_UNIQUE` (`TIN` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Film`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Film` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Film` (
  `Title` VARCHAR(45) NOT NULL,
  `Year` YEAR NOT NULL,
  `Runtime` TIME NOT NULL,
  `Country` VARCHAR(45) NOT NULL,
  `Colour` ENUM('Coloured', 'Black and white') NOT NULL,
  `Film_Title` VARCHAR(45) NOT NULL,
  `Film_Year` INT NOT NULL,
  `Director_TIN` INT NOT NULL,
  UNIQUE INDEX `Title_UNIQUE` (`Title` ASC) VISIBLE,
  PRIMARY KEY (`Title`, `Year`),
  INDEX `fk_Film_Film1_idx` (`Film_Title` ASC, `Film_Year` ASC) VISIBLE,
  INDEX `fk_Film_Director1_idx` (`Director_TIN` ASC) VISIBLE,
  CONSTRAINT `fk_Film_Film1`
    FOREIGN KEY (`Film_Title` , `Film_Year`)
    REFERENCES `mydb`.`Film` (`Title` , `Year`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Film_Director1`
    FOREIGN KEY (`Director_TIN`)
    REFERENCES `mydb`.`Director` (`TIN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Script_Writer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Script_Writer` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Script_Writer` (
  `TIN` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Surname` VARCHAR(45) NOT NULL,
  `Birth_Date` DATE NOT NULL,
  `Gender` ENUM('Male', 'Female') NOT NULL,
  `Nationality` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`TIN`),
  UNIQUE INDEX `TIN_UNIQUE` (`TIN` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Crew_Member`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Crew_Member` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Crew_Member` (
  `TIN` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Surname` VARCHAR(45) NOT NULL,
  `Specialty` ENUM('Set designer', 'Sound mixer', 'Cameraman', 'Costume maker', 'Photographer', 'Makeup Artist', 'Montage', 'Set Manager') NOT NULL,
  `Age` INT NOT NULL,
  `Nationality` VARCHAR(45) NOT NULL,
  UNIQUE INDEX `TIN_UNIQUE` (`TIN` ASC) VISIBLE,
  PRIMARY KEY (`TIN`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Studio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Studio` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Studio` (
  `Name` VARCHAR(45) NOT NULL,
  `Location` VARCHAR(45) NOT NULL,
  `Area` FLOAT NOT NULL,
  `Country` VARCHAR(45) NOT NULL,
  `Company_Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Name`, `Location`),
  UNIQUE INDEX `Name_UNIQUE` (`Name` ASC) VISIBLE,
  UNIQUE INDEX `Location_UNIQUE` (`Location` ASC) VISIBLE,
  INDEX `fk_Studio_Company1_idx` (`Company_Name` ASC) VISIBLE,
  CONSTRAINT `fk_Studio_Company1`
    FOREIGN KEY (`Company_Name`)
    REFERENCES `mydb`.`Company` (`Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Photograph`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Photograph` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Photograph` (
  `Description` TEXT NOT NULL,
  PRIMARY KEY (`Description`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Nomination`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Nomination` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Nomination` (
  `Nomination_number` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Year` YEAR NOT NULL,
  `Category` VARCHAR(45) NOT NULL,
  `Movie` VARCHAR(45) NOT NULL,
  `is_Winner` TINYINT(1) NOT NULL,
  `Actor_TIN` INT NOT NULL,
  `Script_Writer_TIN` INT NOT NULL,
  `Director_TIN` INT NOT NULL,
  `Crew_Member_TIN` INT NOT NULL,
  `Film_Title` VARCHAR(45) NOT NULL,
  `Film_Year` INT NOT NULL,
  INDEX `fk_Nomination_Actor1_idx` (`Actor_TIN` ASC) VISIBLE,
  INDEX `fk_Nomination_Script_Writer1_idx` (`Script_Writer_TIN` ASC) VISIBLE,
  INDEX `fk_Nomination_Director1_idx` (`Director_TIN` ASC) VISIBLE,
  INDEX `fk_Nomination_Crew_Member1_idx` (`Crew_Member_TIN` ASC) VISIBLE,
  INDEX `fk_Nomination_Film1_idx` (`Film_Title` ASC, `Film_Year` ASC) VISIBLE,
  PRIMARY KEY (`Nomination_number`),
  CONSTRAINT `fk_Nomination_Actor1`
    FOREIGN KEY (`Actor_TIN`)
    REFERENCES `mydb`.`Actor` (`TIN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Nomination_Script_Writer1`
    FOREIGN KEY (`Script_Writer_TIN`)
    REFERENCES `mydb`.`Script_Writer` (`TIN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Nomination_Director1`
    FOREIGN KEY (`Director_TIN`)
    REFERENCES `mydb`.`Director` (`TIN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Nomination_Crew_Member1`
    FOREIGN KEY (`Crew_Member_TIN`)
    REFERENCES `mydb`.`Crew_Member` (`TIN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Nomination_Film1`
    FOREIGN KEY (`Film_Title` , `Film_Year`)
    REFERENCES `mydb`.`Film` (`Title` , `Year`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Oscar`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Oscar` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Oscar` (
  `Award` ENUM('Best Movie', 'Best Actor', 'Best Actress', 'Best supporting Actor', 'Best supporting Actress', 'Best Director', 'Best original screenplay', 'Best Adapted Screenplay', 'Best foreign film', 'Best Visual Effects', 'Best Picture', 'Best Costume Design', 'Best Documentary', 'Best short Documentary', 'Best Film Editing', 'Best Makeup', 'Best Sound Editing', 'Best original song', 'Best Animated Film', 'Best Animated short Film', 'Best short Film') NOT NULL,
  `Winner` BIGINT NOT NULL,
  `Year` YEAR NOT NULL,
  PRIMARY KEY (`Award`, `Winner`),
  INDEX `fk_Oscar_Nomination1_idx` (`Winner` ASC) VISIBLE,
  INDEX `fk_Oscar_Nomination2_idx` (`Winner` ASC, `Year` ASC) VISIBLE,
  INDEX `fk_Oscar_Nomination2_idx1` (`Year` ASC) VISIBLE,
  CONSTRAINT `fk_Oscar_Nomination1`
    FOREIGN KEY (`Winner`)
    REFERENCES `mydb`.`Nomination` (`Nomination_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Oscar_Nomination2`
    FOREIGN KEY (`Year`)
    REFERENCES `mydb`.`Nomination` (`Year`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Academy_Member`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Academy_Member` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Academy_Member` (
  `Actor_TIN` INT NOT NULL,
  `Script_Writer_TIN` INT NOT NULL,
  `Director_TIN` INT NOT NULL,
  `Crew_Member_TIN` INT NOT NULL,
  PRIMARY KEY (`Actor_TIN`, `Script_Writer_TIN`, `Director_TIN`, `Crew_Member_TIN`),
  INDEX `fk_Academy_Member_Actor1_idx` (`Actor_TIN` ASC) VISIBLE,
  INDEX `fk_Academy_Member_Script_Writer1_idx` (`Script_Writer_TIN` ASC) VISIBLE,
  INDEX `fk_Academy_Member_Director1_idx` (`Director_TIN` ASC) VISIBLE,
  INDEX `fk_Academy_Member_Crew_Member1_idx` (`Crew_Member_TIN` ASC) VISIBLE,
  CONSTRAINT `fk_Academy_Member_Actor1`
    FOREIGN KEY (`Actor_TIN`)
    REFERENCES `mydb`.`Actor` (`TIN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Academy_Member_Script_Writer1`
    FOREIGN KEY (`Script_Writer_TIN`)
    REFERENCES `mydb`.`Script_Writer` (`TIN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Academy_Member_Director1`
    FOREIGN KEY (`Director_TIN`)
    REFERENCES `mydb`.`Director` (`TIN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Academy_Member_Crew_Member1`
    FOREIGN KEY (`Crew_Member_TIN`)
    REFERENCES `mydb`.`Crew_Member` (`TIN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Genre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Genre` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Genre` (
  `Genre` ENUM('Comedy', 'Drama', 'Adventure', 'Action', 'Sci-fi', 'Romantic Comedy', 'Musical', 'Horror', 'Mystery', 'Cartoon', 'Documentary') NOT NULL,
  PRIMARY KEY (`Genre`),
  UNIQUE INDEX `Genre_UNIQUE` (`Genre` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Voted_By`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Voted_By` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Voted_By` (
  `Votes` INT NOT NULL,
  `Academy_Member_Actor_TIN` INT NOT NULL,
  `Academy_Member_Script_Writer_TIN` INT NOT NULL,
  `Academy_Member_Director_TIN` INT NOT NULL,
  `Academy_Member_Crew_Member_TIN` INT NOT NULL,
  `Nomination_Nomination_number` BIGINT NOT NULL,
  PRIMARY KEY (`Academy_Member_Actor_TIN`, `Academy_Member_Script_Writer_TIN`, `Academy_Member_Director_TIN`, `Academy_Member_Crew_Member_TIN`, `Nomination_Nomination_number`),
  INDEX `fk_Vote_Nomination1_idx` (`Nomination_Nomination_number` ASC) VISIBLE,
  CONSTRAINT `fk_Vote_Academy_Member1`
    FOREIGN KEY (`Academy_Member_Actor_TIN` , `Academy_Member_Script_Writer_TIN` , `Academy_Member_Director_TIN` , `Academy_Member_Crew_Member_TIN`)
    REFERENCES `mydb`.`Academy_Member` (`Actor_TIN` , `Script_Writer_TIN` , `Director_TIN` , `Crew_Member_TIN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Vote_Nomination1`
    FOREIGN KEY (`Nomination_Nomination_number`)
    REFERENCES `mydb`.`Nomination` (`Nomination_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Film_has_Genre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Film_has_Genre` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Film_has_Genre` (
  `Film_Title` VARCHAR(45) NOT NULL,
  `Film_Year` INT NOT NULL,
  `Genre_Genre` ENUM('Comedy', 'Drama', 'Adventure', 'Action', 'Sci-fi', 'Romantic Comedy', 'Musical', 'Horror', 'Mystery', 'Cartoon', 'Documentary') NOT NULL,
  INDEX `fk_Film_has_Genre_Genre1_idx` (`Genre_Genre` ASC) VISIBLE,
  INDEX `fk_Film_has_Genre_Film1_idx` (`Film_Title` ASC, `Film_Year` ASC) VISIBLE,
  PRIMARY KEY (`Film_Title`, `Film_Year`, `Genre_Genre`),
  CONSTRAINT `fk_Film_has_Genre_Film1`
    FOREIGN KEY (`Film_Title` , `Film_Year`)
    REFERENCES `mydb`.`Film` (`Title` , `Year`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Film_has_Genre_Genre1`
    FOREIGN KEY (`Genre_Genre`)
    REFERENCES `mydb`.`Genre` (`Genre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Production`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Production` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Production` (
  `Company_Name` VARCHAR(45) NOT NULL,
  `Film_Title` VARCHAR(45) NOT NULL,
  `Film_Year` YEAR NOT NULL,
  `Film_Series` TINYINT(1) NOT NULL,
  PRIMARY KEY (`Company_Name`, `Film_Title`, `Film_Year`),
  INDEX `fk_Production_Film1_idx` (`Film_Title` ASC, `Film_Year` ASC) VISIBLE,
  CONSTRAINT `fk_Production_Company1`
    FOREIGN KEY (`Company_Name`)
    REFERENCES `mydb`.`Company` (`Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Production_Film1`
    FOREIGN KEY (`Film_Title` , `Film_Year`)
    REFERENCES `mydb`.`Film` (`Title` , `Year`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Part`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Part` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Part` (
  `Part_id` ENUM('Male Leading', 'Female Leading', 'Male Supporting', 'Female Supporting') NOT NULL,
  `Decription` VARCHAR(45) NOT NULL,
  `Film_Title` VARCHAR(45) NOT NULL,
  `Film_Year` YEAR NOT NULL,
  `Actor_TIN` INT NOT NULL,
  PRIMARY KEY (`Decription`, `Film_Title`, `Film_Year`),
  INDEX `fk_Actor_has_Film_Film1_idx` (`Film_Title` ASC, `Film_Year` ASC) VISIBLE,
  INDEX `fk_Actor_has_Film_Actor1_idx` (`Actor_TIN` ASC) VISIBLE,
  CONSTRAINT `fk_Actor_has_Film_Actor1`
    FOREIGN KEY (`Actor_TIN`)
    REFERENCES `mydb`.`Actor` (`TIN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Actor_has_Film_Film1`
    FOREIGN KEY (`Film_Title` , `Film_Year`)
    REFERENCES `mydb`.`Film` (`Title` , `Year`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Actor_has_Photograph`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Actor_has_Photograph` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Actor_has_Photograph` (
  `Actor_TIN` INT NOT NULL,
  `Photograph_Description` TEXT NOT NULL,
  PRIMARY KEY (`Actor_TIN`, `Photograph_Description`),
  INDEX `fk_Actor_has_Photograph_Photograph1_idx` (`Photograph_Description` ASC) VISIBLE,
  INDEX `fk_Actor_has_Photograph_Actor1_idx` (`Actor_TIN` ASC) VISIBLE,
  CONSTRAINT `fk_Actor_has_Photograph_Actor1`
    FOREIGN KEY (`Actor_TIN`)
    REFERENCES `mydb`.`Actor` (`TIN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Actor_has_Photograph_Photograph1`
    FOREIGN KEY (`Photograph_Description`)
    REFERENCES `mydb`.`Photograph` (`Description`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Script_Writer_has_Photograph`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Script_Writer_has_Photograph` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Script_Writer_has_Photograph` (
  `Script_Writer_TIN` INT NOT NULL,
  `Photograph_Description` TEXT NOT NULL,
  PRIMARY KEY (`Script_Writer_TIN`, `Photograph_Description`),
  INDEX `fk_Script_Writer_has_Photograph_Photograph1_idx` (`Photograph_Description` ASC) VISIBLE,
  INDEX `fk_Script_Writer_has_Photograph_Script_Writer1_idx` (`Script_Writer_TIN` ASC) VISIBLE,
  CONSTRAINT `fk_Script_Writer_has_Photograph_Script_Writer1`
    FOREIGN KEY (`Script_Writer_TIN`)
    REFERENCES `mydb`.`Script_Writer` (`TIN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Script_Writer_has_Photograph_Photograph1`
    FOREIGN KEY (`Photograph_Description`)
    REFERENCES `mydb`.`Photograph` (`Description`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Film_has_Script_Writers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Film_has_Script_Writers` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Film_has_Script_Writers` (
  `Film_Title` VARCHAR(100) NOT NULL,
  `Film_Year` YEAR NOT NULL,
  `Script_Writer_TIN` INT NOT NULL,
  PRIMARY KEY (`Film_Year`, `Script_Writer_TIN`, `Film_Title`),
  INDEX `fk_Film_has_Script_Writer_Script_Writer1_idx` (`Script_Writer_TIN` ASC) VISIBLE,
  INDEX `fk_Film_has_Script_Writer_Film1_idx` (`Film_Title` ASC, `Film_Year` ASC) VISIBLE,
  CONSTRAINT `fk_Film_has_Script_Writer_Film1`
    FOREIGN KEY (`Film_Title` , `Film_Year`)
    REFERENCES `mydb`.`Film` (`Title` , `Year`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Film_has_Script_Writer_Script_Writer1`
    FOREIGN KEY (`Script_Writer_TIN`)
    REFERENCES `mydb`.`Script_Writer` (`TIN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Director_has_Photograph`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Director_has_Photograph` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Director_has_Photograph` (
  `Director_TIN` INT NOT NULL,
  `Photograph_Description` TEXT NOT NULL,
  PRIMARY KEY (`Director_TIN`, `Photograph_Description`),
  INDEX `fk_Director_has_Photograph_Photograph1_idx` (`Photograph_Description` ASC) VISIBLE,
  INDEX `fk_Director_has_Photograph_Director1_idx` (`Director_TIN` ASC) VISIBLE,
  CONSTRAINT `fk_Director_has_Photograph_Director1`
    FOREIGN KEY (`Director_TIN`)
    REFERENCES `mydb`.`Director` (`TIN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Director_has_Photograph_Photograph1`
    FOREIGN KEY (`Photograph_Description`)
    REFERENCES `mydb`.`Photograph` (`Description`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Crew_Member_has_Photograph`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Crew_Member_has_Photograph` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Crew_Member_has_Photograph` (
  `Crew_Member_TIN` INT NOT NULL,
  `Photograph_Description` TEXT NOT NULL,
  PRIMARY KEY (`Crew_Member_TIN`, `Photograph_Description`),
  INDEX `fk_Crew_Member_has_Photograph_Photograph1_idx` (`Photograph_Description` ASC) VISIBLE,
  INDEX `fk_Crew_Member_has_Photograph_Crew_Member1_idx` (`Crew_Member_TIN` ASC) VISIBLE,
  CONSTRAINT `fk_Crew_Member_has_Photograph_Crew_Member1`
    FOREIGN KEY (`Crew_Member_TIN`)
    REFERENCES `mydb`.`Crew_Member` (`TIN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Crew_Member_has_Photograph_Photograph1`
    FOREIGN KEY (`Photograph_Description`)
    REFERENCES `mydb`.`Photograph` (`Description`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Academy_President`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Academy_President` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Academy_President` (
  `Term_of_Office` YEAR NOT NULL,
  `Academy_Member_Actor_TIN` INT NOT NULL,
  `Academy_Member_Script_Writer_TIN` INT NOT NULL,
  `Academy_Member_Director_TIN` INT NOT NULL,
  `Academy_Member_Crew_Member_TIN` INT NOT NULL,
  INDEX `fk_Board_of_Governors_Academy_Member1_idx` (`Academy_Member_Actor_TIN` ASC, `Academy_Member_Script_Writer_TIN` ASC, `Academy_Member_Director_TIN` ASC, `Academy_Member_Crew_Member_TIN` ASC) VISIBLE,
  PRIMARY KEY (`Academy_Member_Actor_TIN`, `Academy_Member_Script_Writer_TIN`, `Academy_Member_Director_TIN`, `Academy_Member_Crew_Member_TIN`, `Term_of_Office`),
  CONSTRAINT `fk_Board_of_Governors_Academy_Member1`
    FOREIGN KEY (`Academy_Member_Actor_TIN` , `Academy_Member_Script_Writer_TIN` , `Academy_Member_Director_TIN` , `Academy_Member_Crew_Member_TIN`)
    REFERENCES `mydb`.`Academy_Member` (`Actor_TIN` , `Script_Writer_TIN` , `Director_TIN` , `Crew_Member_TIN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Film_has_Crew_Member`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Film_has_Crew_Member` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Film_has_Crew_Member` (
  `Film_Title` VARCHAR(45) NOT NULL,
  `Film_Year` YEAR NOT NULL,
  `Crew_Member_TIN` INT NOT NULL,
  PRIMARY KEY (`Film_Title`, `Film_Year`, `Crew_Member_TIN`),
  INDEX `fk_Film_has_Crew_Member_Crew_Member1_idx` (`Crew_Member_TIN` ASC) VISIBLE,
  INDEX `fk_Film_has_Crew_Member_Film1_idx` (`Film_Title` ASC, `Film_Year` ASC) VISIBLE,
  CONSTRAINT `fk_Film_has_Crew_Member_Film1`
    FOREIGN KEY (`Film_Title` , `Film_Year`)
    REFERENCES `mydb`.`Film` (`Title` , `Year`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Film_has_Crew_Member_Crew_Member1`
    FOREIGN KEY (`Crew_Member_TIN`)
    REFERENCES `mydb`.`Crew_Member` (`TIN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
